#%RAML 1.0 DataType
type: object
id: string
emailAddress: string
companyName?: string
jobLocation?: string
jobTitle?: string
jobExperienceLevel: string
jobType: string
tags?: string
salaryrangeFrom: float
salaryrangeTo: float
jobDescription: string