#%RAML 1.0 Library
types:
  Notification: !include Notification.raml
  Card: !include Card.raml
  Error: !include Error.raml
  Email: !include Email.raml
  Member: !include Member.raml
  Document: !include Document.raml
  Pitch: !include Pitch.raml
  Section: !include Section.raml
