#%RAML 1.0
---
title: GR8DI Website API
baseUri: http://api.gr8di.com
version: v1
protocols: [HTTPS]
mediaType: application/json

securitySchemes:
  basicAuth: !include securitySchemes/Basic.raml

uses:
  types: !include libraries/types/types.raml

traits:
  pageable: !include traits/pageable.raml
  searchable: !include traits/searchable.raml
  sortable: !include traits/sortable.raml


/examplepages:
  /{language}:
    get:
      description: gets all pages
        responses:
          200:
            body:
              application/json:
                type: !include libraries/types/examplepage.raml
                example: !include examples/pages.json
          204:
            description: No Content
          400:
            body:
              application/json:
                type: !include libraries/types/Error.raml
                example: !include examples/error.json

  /{id}:
    get:
    securedBy: basicAuth
      description: get a examplepage by its id
        responses:
          200:
            body:
              application/json:
                type: !include libraries/types/examplepage.raml
                example: !include examples/document.json
          204:
            description: No Content
          400:
            body:
              application/json:
                type: !include libraries/types/Error.raml
                example: !include examples/error.json

    put:
      securedBy: basicAuth
      description: Update a new examplepage
      body:
        type: !include libraries/types/examplepage.raml
        example: !include examples/document.json
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request.
          body:
            application/json:
              type: !include libraries/types/Error.raml
              example: !include examples/error.json

    delete:
      securedBy: basicAuth
      description: Delete examplepage
      body:
        type: !include libraries/types/examplepage.raml
        example: !include examples/document.json
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request.
          body:
            application/json:
              type: !include libraries/types/Error.raml
              example: !include examples/error.json

  post:
    securedBy: basicAuth
    description: Creates a new examplepage
    body:
      type: !include libraries/types/examplepage.raml
      example: !include examples/document.json
    responses:
      202:
        description: Accepted
      400:
        description: Bad Request.
        body:
          application/json:
            type: !include libraries/types/Error.raml
            example: !include examples/error.json

/messages:
    resourceTypes:
        collection:
            description: Contains all sets of messages
            get:
              securedBy: basicAuth
              description: gets all messages that match query parameter
              queryParameters:
                senderEmail:
                  type: string
                  required: true
                  example: "jobs@awesome.io"
                message:
                  type: string
                  required: true
                  example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec vehicula dolor, sit amet molestie ..."
                topic:
                  type: string
                  required: true
                  example: "Neque porro quisquam"

                responses:
                  200:
                    body:
                      application/json:
                        types: !include examples/Email.json
                        example: !include examples/emails.json
            post:
              description: creates a new message
              body:
                application/json:
                  type: !include libraries/types/Email.raml
              responses:
                  202:
                      body:
                          application/json:
                              type: !include libraries/types/Email.raml
                              example: !include examples/emails.json
	/{messageId}:
      collection-item:
        get:
          securedBy: basicAuth
          description: gets a particular message by its id
          responses:
            200:
              body:
                application/json:
                  example: !include examples/emails.json
            404:
              body:
                application/json:
                  example:!include examples/error.json
        delete:
          securedBy: basicAuth
          description: delete message by id

/jobs:
	description: Job entity
	get:
      description: Get all job posts
      response:
        200:
         description: Ok

        404:
         description: Not found
	post:
	    description: Creates new Job
        body:
          type: !include libraries/types/Job.raml
            example: !include examples/job.json
        responses:
          202:
            description: Accepted
          400:
            description: Bad Request.
              body:
                application/json:
                  type: !include libraries/types/Error.raml
                  example: !include examples/error.json

	/{jobId}:
      get:
      securedBy: basicAuth
        description: Get a job with jobId = {jobId}
        body:
          application/json:
              type: message
        responses:
          200:
             body:
                 application/json:
                    type: !include libraries/types/Error.raml
                    example: !include examples/error.json

      put:
        securedBy: basicAuth
          description: Updates a Job
          body:
            type: !include libraries/types/Job.raml
            example: !include examples/job.json
          responses:
            202:
              description: Accepted
            404:
              description: Not found
              body:
                application/json:
                  type: !include libraries/types/Error.raml
                  example: !include examples/error.json

      delete:
        securedBy: basicAuth
          description: Delete Job
          body:
            type: !include libraries/types/Job.raml
            example: !include examples/job.json
          responses:
            202:
              description: Accepted
            404:
              description: Not found
              body:
                application/json:
                  type: !include libraries/types/Error.raml
                  example: !include examples/error.json

/reports:
  post:
    /{statsId}:
      get:
        description: displays the statistics for a particular examplepage
        responses:
          200:
            body:
              application/json:
                example: !include examples/status.json


          404:
            body:
              application/json:
                example: !include examples/error.json

  put:

/mentor:
  get:
    description: Get all mentors
    queryParameters:
      name:
        type: string
        required: true
        example: "johndoe"
    responses:
      200:
        description: OK
        body:
          application/json:
            type: !include libraries/types/Mentor.raml
            example: !include examples/mentor.json
      404:
        description: Not found

  post:
    description: Creates new Mentor
    body:
      type: !include libraries/types/Mentor.raml
      example: !include examples/mentor.json
    responses:
      202:
        description: Accepted
      400: Bad Request
        body:
          application/json:
            example: !include examples/error.json

  put:
    securedBy: basicAuth
      description: Updates a Mentor
      body:
        type: !include libraries/types/Mentor.raml
        example: !include examples/mentor.json
      responses:
        202:
          description: Accepted
        404:
          description: Not found
          body:
            application/json:
              type: !include libraries/types/Mentor.raml
              example: !include examples/error.json
  delete:
    securedBy: basicAuth
      description: Delete Mentor
      body:
         type: !include libraries/types/Mentor.raml
        example: !include examples/mentor.json
      responses:
        202:
          description: Accepted
        404:
          description: Not found
          body:
            application/json:
              type: !include libraries/types/Mentor.raml
              example: !include examples/error.json

/mentee:
  get:
    description: Get all mentees
    queryParameters:
      name:
        type: string
        required: true
        example: "johndoe"
    responses:
      200:
        description: OK
        body:
          application/json:
            type: !include libraries/types/Mentee.raml
            example: !include examples/mentee.json
      404:
        description: Not found

  post:
    description: Creates new Mentee
    body:
      type: !include libraries/types/Mentee.raml
      example: !include examples/mentee.json
    responses:
      202:
        description: Accepted
      400: Bad Request
        body:
          application/json:
            example: !include examples/error.json

  put:
    securedBy: basicAuth
      description: Updates a Mentee
      body:
        type: !include libraries/types/Mentee.raml
        example: !include examples/mentee.json
      responses:
        202:
          description: Accepted
        404:
          description: Not found
          body:
            application/json:
              type: !include libraries/types/Mentee.raml
              example: !include examples/error.json
  delete:
    securedBy: basicAuth
      description: Delete Mentee
      body:
         type: !include libraries/types/Mentee.raml
        example: !include examples/mentee.json
      responses:
        202:
          description: Accepted
        404:
          description: Not found
          body:
            application/json:
              type: !include libraries/types/Mentee.raml
              example: !include examples/error.json